### PR TITLE
Safely call `set` in aptosDataCache

### PR DESCRIPTION
**Pull request by ranger8888**

### CODE REVIEW

**Comment by Manahip** [comment]
We're actually trying to duplicate move vm's default behavior. With Move VM, if you try use move_to when account already has that resource, it will abort.

Maybe add `overwrite` as an optional argument for humans to use? (original intention was that it'll only be used by generated code)

**Comment by ranger8888** [comment]
Isn't `overwrite` already an optional argument?

The main reason I am introducing this PR is because when calling `load*` for the second time, this error gets triggered.

**Comment by Manahip** [comment]
got it! I'll send a separate patch!

**Comment by Manahip** [comment]
should've fixed in latest commit!

**Pull request closed without merging**
